"""I deleted all the tables

Revision ID: 07c4e54e3b0a
Revises: de21732fd204
Create Date: 2021-03-06 22:25:25.283197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c4e54e3b0a'
down_revision = 'de21732fd204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
