"""I deleted all the tables

Revision ID: 208aec4bed0a
Revises: 76d776504d25
Create Date: 2021-03-06 23:31:28.336124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208aec4bed0a'
down_revision = '76d776504d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
