"""empty message

Revision ID: 3e20e7bac34c
Revises: d8bf64826522
Create Date: 2020-12-01 10:56:19.146868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e20e7bac34c'
down_revision = 'd8bf64826522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
