"""I deleted all the tables

Revision ID: 3f43b5d7357f
Revises: c1d08a2b1cec
Create Date: 2021-03-06 21:07:12.619599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f43b5d7357f'
down_revision = 'c1d08a2b1cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
