"""I deleted all the tables

Revision ID: 764c48e0a9c7
Revises: 3f43b5d7357f
Create Date: 2021-03-06 21:31:57.366801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764c48e0a9c7'
down_revision = '3f43b5d7357f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
