"""I deleted all the tables

Revision ID: 76d776504d25
Revises: b1e0dd42c5e3
Create Date: 2021-03-06 23:03:46.733441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d776504d25'
down_revision = 'b1e0dd42c5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
