"""I deleted all the tables

Revision ID: a58b4ee5f9ac
Revises: 2b91ebbeae00
Create Date: 2021-02-27 21:08:16.138762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58b4ee5f9ac'
down_revision = '2b91ebbeae00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
