"""I deleted all the tables

Revision ID: b1e0dd42c5e3
Revises: 07c4e54e3b0a
Create Date: 2021-03-06 22:50:31.904412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e0dd42c5e3'
down_revision = '07c4e54e3b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
