"""I deleted all the tables

Revision ID: b24d40a9aff2
Revises: 3f86fe61ebf1
Create Date: 2021-02-21 21:44:34.964841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24d40a9aff2'
down_revision = '3f86fe61ebf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
