"""I deleted all the tables

Revision ID: c1d08a2b1cec
Revises: a58b4ee5f9ac
Create Date: 2021-02-27 21:11:07.752846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d08a2b1cec'
down_revision = 'a58b4ee5f9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
