"""empty message

Revision ID: d8bf64826522
Revises: b60bb67d1758
Create Date: 2020-12-01 09:58:50.973506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bf64826522'
down_revision = 'b60bb67d1758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_ibfk_1', 'data', type_='foreignkey')
    op.create_table(
        "data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("assigned_user_id", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("filename", sa.String(length=100), nullable=False),
        sa.Column("original_filename", sa.String(length=100), nullable=False),
        sa.Column("reference_transcription", sa.Text(), nullable=True),
        sa.Column("is_marked_for_review", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('data_ibfk_1', 'data', 'user', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###
