"""I deleted all the tables

Revision ID: de21732fd204
Revises: 764c48e0a9c7
Create Date: 2021-03-06 22:00:58.665287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de21732fd204'
down_revision = '764c48e0a9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
